### ISSUE TITLE
Where do you call MerchantinitializationApi ?

### ISSUE THREAD

**Issue by cesar-sebastian** [marcoshoya/MasterpassBundle#5]
Hello Marcos,

Are you missing a call to the MerchantinitializationApi  service ?

1. Call Request Token Service - 
 $requestToken = $service->getRequestToken();

2. Call Shopping Cart Service -
$shoppingCart = $service->postShoppingCartData($requestToken, $shoppingCartXml);

3. Call Merchant Initialization Service - 
Where?

Thanks

**Comment by marcoshoya** [comment]
hi @CesarCarrazana 

When this bundle was developed, API didn't have such a call in the specs, although you are free to send a pull request. Is the integration broken ?

**Comment by cesar-sebastian** [comment]
yes it broke :(

**Comment by marcoshoya** [comment]
MerchantInitialization service was added. 
You can call it by invoking the method postMerchantInitData from MasterpassService class.

Cheers

**Comment by cesar-sebastian** [comment]
Thank you very much!!

Regards!


2017-04-29 18:17 GMT-03:00 Marcos Joia <notifications@github.com>:

**Comment by cesar-sebastian** [comment]
Problem with monolog version.

We have

"symfony/monolog-bundle": "~2.4",

You have 3.

Can you change the version of the library?

Regards




2017-04-29 18:21 GMT-03:00 César Sebastián Carrazana <
cesarcarrazana@gmail.com>:

**Comment by cesar-sebastian** [comment]
https://github.com/marcoshoya/MasterpassBundle/commit/c23dced37683b43300432d93bbbba20ccee69a45


You can support previous versions of monolog ? from ~2.4

Regards

2017-05-03 13:31 GMT-03:00 César Sebastián Carrazana <
cesarcarrazana@gmail.com>:

**Comment by marcoshoya** [comment]
Unfortunately it can't. This bundle is not compatible with Symfony 2.x
You will be required to upgrade your monolog as well as the framework itself to version 3.

Cheers
