### ISSUE TITLE
Method - MerchantTransaction

### ISSUE THREAD

**Issue by cesar-sebastian** [marcoshoya/MasterpassBundle#7]
You can implement the method MerchantTransaction ? It is necessary to finish the process

**Comment by marcoshoya** [comment]
Don't think transaction is missing. Check methods from Service class again.

**Comment by cesar-sebastian** [comment]
[Document
](https://developer.mastercard.com/documentation/masterpass-merchant-integration#standard-checkout)
9. Log transactions with Masterpass 

use Mastercard\Masterpass\Merchant\Api\PostbackApi;
use Mastercard\Masterpass\Merchant\Model\MerchantTransaction;
use Mastercard\Masterpass\Merchant\Model\MerchantTransactions;

# Create an instance of MerchantTransactions
     $request = new MerchantTransactions(
        	array(
        		'MerchantTransactions' => new MerchantTransaction( 
        			array(
        				'TransactionId' => “YOUR_TRANSACTION_ID”
        				'PurchaseDate' => '2016-05-27T12:38:40.479+05:30',
        				'ExpressCheckoutIndicator' => false,
        				'ApprovalCode' => 'sample',
        				'TransactionStatus' => 'Success',
        				'OrderAmount' => 76239,
        				'Currency' => 'USD',
        				'ConsumerKey' => "YOUR_CONSUMER_KEY"
        				)
        			 )
        			
        		)
        	 );
    #Call Merchant transaction service api
    $merchantTransactionsResponse = PostbackApi::create($merchantTransactions);

**Comment by marcoshoya** [comment]
See example in the documentation

https://github.com/marcoshoya/MasterpassBundle/blob/master/Controller/MasterpassController.php#L218
